### ISSUE TITLE
REUSE improvements

### ISSUE THREAD

**Issue by lu-zero** [SoftengPoliTo/ci-generate#22]
- [ ] Populate the `Copyright:` correctly
- [ ] Populate the `Upstream-Contact:` correctly
- [ ] Populate the `Source:` correctly

See `templates/dep5`:
```yaml
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: {{ reuse.name }}
Upstream-Contact: Name Surname <mail@example.com>
Source: https://your/project/link

Files: *
Copyright: 2019 Translation Company
License: {{ reuse.id }}
```
